spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

application.title=online-banking-rest-api
application.version=1.0.0
server.port=8080

logging.level.org.springframework=info
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

onlinebankingrestapi.jwt.security.app.key=${JWT_KEY}
onlinebankingrestapi.jwt.security.expire.time=86400000

cbarkinozer.kafka.adddress=localhost:9092
cbarkinozer.kafka.topic=logs
cbarkinozer.kafka.group-id=onlinebankingrestapi